### ISSUE TITLE
Can't launch Vice, error parsing command line options

### ISSUE THREAD

**Issue by Gavin-Williams** [GeorgRottensteiner/C64Studio#100]
When I try to run a simple basic program, I can't even get Vice to launch. I get the following output...

> Determined D:\Projects - C64Studio\SetupTests\Loader.bas as active document Running build on D:\Projects - C64Studio\SetupTests\Loader.bas Build successful, 0 warnings, 0 errors encountered Start address $0801 to $0811, size 17 bytes Memory Map: Compiled to file D:\Projects - C64Studio\SetupTests\Loader.prg, 19 bytes Running D:\Projects - C64Studio\SetupTests\Loader.bas Calling E:\Emulators\GTK3VICE-3.6.1-win64\bin\x64sc.exe with -drive8truedrive +virtualdev "D:\Projects - C64Studio\SetupTests\Loader.prg" Hotkeys: Initializing. Hotkeys: Parsing C64 hotkeys file: Hotkeys: OK. ffmpeg avformat lib has version 3a4c64, VICE expects 3a4c64: full match ffmpeg  avcodec lib has version 3a8664, VICE expects 3a8664: full match ffmpeg   avutil lib has version 384664, VICE expects 384664: full match ffmpeg  swscale lib has version 050964, VICE expects 050964: full match ffmpeg swresample lib has version 030964, VICE expects 030964: full match Detecting DLL based HardSID boards. Initializing chip model "MOS8565" (63 cycles per line, 312 raster lines). VSP Bug: safe channels are: 27. Emulation of memory corruption is disabled. Option '+virtualdev' is ambiguous. Error parsing command-line options, bailing out. For help use '-help' Run exited with result code -1

The output regarding command-line options...

> Calling E:\Emulators\GTK3VICE-3.6.1-win64\bin\x64sc.exe with -drive8truedrive +virtualdev "D:\Projects - C64Studio\SetupTests\Loader.prg"

These are the default command line options generated by the wizard. It looks like the options: -drive8truedrive +virtualdev are garbage, and need to be removed. When I look at C64 Studio preferences, it has a list of what looks like hardcoded runtime arguments. How can i disable the true drive on option? I just deleted the text and it worked, I hope I don't need that text later.

**Comment by GeorgRottensteiner** [comment]
Damn, with the latest version 7.6 the wizard should set the proper command line arguments, but I messed up (note the missing 8)
True Drive On: -drive8truedrive +virtualdev8 
True Drive Off: +drive8truedrive -virtualdev8 

Fixed with commit #56a4f37afcdf0c5873865da743ced9b9f9a3a34b
