### ISSUE TITLE
Solution / Project creation doesn't seem to match what was configured.

### ISSUE THREAD

**Issue by Gavin-Williams** [GeorgRottensteiner/C64Studio#102]
When I perform the following...

1. File > New Solution : 
        Solution Name = JacksProjects
        Solution Base Folder = D:\C64\Projects_C64Studio
        Create new folder for solution = yes
        Create project in separate folder = yes
        Project Name = Questions
        Create repository = no
        
I don't see any project entry in the solution explorer. I only see:
    
    JacksProjects // the solution node
    
This doesn't make any sense to me, coming from Visual Studio, I expect to see a project node underneath the solution node in the solution explorer. Double-clicking the solution node I get a Project Properties popup and there is an entry there...

    Project File:    D:\C64\Projects_C64Studio\JacksProjects\Question\Questions.c64
    
But it isn't mirrored in the solution explorer. Where is the Questions project? Is this functionality not complete or do you envision it working a different way?

Edit: I chose create repository = no. Is it possible you mean something different to what I think 'repo' means? I take it to mean version control.

**Comment by GeorgRottensteiner** [comment]
Ah, good one! I chose to have no solution node at all, the one visible node is actually the project node, albeit with the wrong label. A stupid bug of mine :)

With "repo" I mean a GIT repository.

**Comment by GeorgRottensteiner** [comment]
Fixed with commit #7a66f0f6b1a27d47b431c2fb5530fcbad9d36c29
