### ISSUE TITLE
How do you type the british pound symbol?

### ISSUE THREAD

**Issue by Thraka** [GeorgRottensteiner/C64Studio#106]
I'm using BASIC-BOSS to compile BASIC but they use the british pound symbol in rem statements to instruct the compiler. I can't figure out how to place it. According to the VICE documentation the `\` key should place it but in the code editor it does nothing.

**Comment by GeorgRottensteiner** [comment]
Per default it's configured to the insert key (the one outside the number block), but you can adapt the mapping under File->Preferences. The default mapping is modeled after VICEs positional mapping; but it could well be that it is not working for every keyboard layout.

![image](https://github.com/GeorgRottensteiner/C64Studio/assets/27266629/28c40d3b-dd2f-484f-a0b5-0852061943d8)

**Comment by Thraka** [comment]
Thanks!
