### ISSUE TITLE
Windows 11 Trojan detected ?

### ISSUE THREAD

**Issue by todddube** [GeorgRottensteiner/C64Studio#108]
Hey @GeorgRottensteiner 
Just downloaded 7.7 release and upon extracting this I got the Windows Defender Trojan detected for MediaManager.exe ? see attached graphic ? I've since deleted and will wait for update on this issue.. 

THANKS
![Screenshot 2024-02-19 131118](https://github.com/GeorgRottensteiner/C64Studio/assets/803463/dbdac7fc-bce5-40a9-b889-672cf471946e)

**Comment by GeorgRottensteiner** [comment]
Thanks for the hint! I've removed the download links and will investigate right now!

**Comment by GeorgRottensteiner** [comment]
I've had virustotal check the file, and there's one potential trojan found, but only by a rather unknown MaxSecure engine. This one seems to come up often in false positives. I'm still currently running a full scan and keep this issue updated.

So far it seems to be a false positive.

![image](https://github.com/GeorgRottensteiner/C64Studio/assets/27266629/4034a15c-6c6b-4afb-9c34-8754054d3ffd)

**Comment by GeorgRottensteiner** [comment]
Full scan with a different site shows all clean:

![image](https://github.com/GeorgRottensteiner/C64Studio/assets/27266629/3b4a4621-cc39-402b-8f2a-94deb3949386)

**Comment by todddube** [comment]
All good - I dont use the 4.8 runtime so ... but I felt it worth opening an issue.. it could be because of something in the code.. neve had this before.. Todd

**Comment by GeorgRottensteiner** [comment]
Well, I have run into false positives every now and then. Better safe than sorry :)

I'll finish the scan and restore the links if that is all that comes up.

**Comment by todddube** [comment]
Thanks for responding e: ***@***.***: 804.432.8850On Feb 19, 2024, at 2:25 PM, Georg Rottensteiner ***@***.***> wrote:﻿
Well, I have run into false positives every now and then. Better safe than sorry :)
I'll finish the scan and restore the links if that is all that comes up.

**Comment by GeorgRottensteiner** [comment]
After a few scan runs I deem the hit a false positive. I'm still keeping an eye on this, thanks for bringing it up!
Safety first!

**Comment by todddube** [comment]
Appreciate you e: ***@***.***: 804.432.8850On Feb 19, 2024, at 3:08 PM, Georg Rottensteiner ***@***.***> wrote:﻿
After a few scan runs I deem the hit a false positive. I'm still keeping an eye on this, thanks for bringing it up!
Safety first!
