### ISSUE TITLE
Outline View (basic source code): double clicking on referenced variables will jump to wrong line of code

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#109]
In version 7.7, 7.6
Editor: Basic V2, Label mode, Symbols On

In the "outline view" I see all my variables under Outline/Global Zone. 
Double clicking on any of them will **jump to wrong places/line numbers** in the basic source code.

Info: In the solution the basic file is marked as active element.

**Comment by GeorgRottensteiner** [comment]
Fixed with commit #105b27eb1d7b262aefdadbb12a03f1d83e02d811,
uploaded to WIP link: https://www.georg-rottensteiner.de/webmisc/C64Studiorelease.zip
