### ISSUE TITLE
No email notifications on Pull requests

### ISSUE THREAD

**Issue by GeorgRottensteiner** [GeorgRottensteiner/C64Studio#11]
Hi,
I seem to receive no email notification when a new pull requests is created by someone. I've double checked my notification settings, and I think I should receive one.
Could there be something else in my profile settings interfering?

Best regards,
Georg Rottensteiner

**Comment by keyworq** [comment]
Are you **watching** your own repository?  If you do, it should be listed at https://github.com/watching

Reference:
  * "[...] watch a repository to receive notifications for new pull requests [...] that are created."
    https://help.github.com/articles/watching-and-unwatching-repositories/

**Comment by GeorgRottensteiner** [comment]
Hi,


Thanks, I wasn't watching it. That was probably the reason then.

I've added it to my watch list.


Thanks for the reply!
