### ISSUE TITLE
Tiny Help WIndow

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#110]
Hi!

I'm working with the C64Studion version 7.8 on Windows 11 Home but I know this bug a long time ago, also in lower versions <7.8:
When I press on F1 for help or open help via the menu Help/Help I get a very small window (see screenshot) with only the close button visible. Long time I didn't even mention that small window on screen and in this situation it seemed to me nothing did happen after clicking on F1.
At least, the small window is resizable normally then. And, unless I close the C64STudio, it keeps its size and position. After restarting the studio the help screen is tiny again.

![Screenshot 2024-05-31 111718](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/644bd0a3-0110-47cd-b07b-4ee968dcf32d)

**Comment by GeorgRottensteiner** [comment]
Huh. I do have that issue sometimes with DockPanelSuite, for some weird reason (Exception?) it fails to restore the size of a window. After a manual resize and restart it ought to come up as expected again though.

Is there any message/error info the Output Display window after a restart?

**Comment by hkramer70** [comment]
One more thing (now): this WIP version is not able to load my solution made with the release version 7.8. I can open it but there is nothing in the solution explorer. Maybe it's because it is "still in dev". I switch back to 7.8 so far.

**Comment by GeorgRottensteiner** [comment]
Regarding the solution format: That seems to be a whole different issue.

The solution format did not change at all. What exactly happens when you open? "Solution Explorer" stays empty, no project or file symbols at all? No message in the "output" window regarding a failure to load something?

**Comment by hkramer70** [comment]
> Regarding the solution format: That seems to be a whole different issue.
> 
> The solution format did not change at all. What exactly happens when you open? "Solution Explorer" stays empty, no project or file symbols at all? No message in the "output" window regarding a failure to load something?

Yes. All of them. Nothing to open, no messages, just empty.

But: I then reopened that solution with the release version 7.8 and the same happened. Even after restarting the PC nothing changed at all. 

Things changed first when I opened the project file (in this solution I only had one project) instead of the sotuion by double clicking on that file in the windows explorer. In the Studio I then clicked on "save" as I saw the normal structure again. A file selector box  appeared to chose a location and a name for the solution file. I selected the existing solution file and from this point all was fine...

**Comment by GeorgRottensteiner** [comment]
Bin auch kein Engländer :)

Das klingt, als wäre das Projekt irgendwie aus der Solution rausgeflogen. Durch das Neu-Speichern ist das Projekt wieder hinzugefügt worden. Interessant, da muss es wohl irgendeine Konstellation geben, wie man das letzte Projekt aus einer Solution rausnehmen kann. Muss ich mal forschen. Danke für die Info, ich behalt's im Auge!
