### ISSUE TITLE
Commander X16 - Sprite colors seem to be wrong.

### ISSUE THREAD

**Issue by jakebullet70** [GeorgRottensteiner/C64Studio#112]
In creating sprites for a Commander X16 program the colors do not seem to be correct.

In the C64Studio
![image](https://github.com/GeorgRottensteiner/C64Studio/assets/14124210/7b3f3f29-45fd-4d42-b2fc-329cc8671d0e)

I save the file as Binary.
It ends up looking like this. Sprite is loading fine but the colors seem to be off.  Am I missing something?
![image](https://github.com/GeorgRottensteiner/C64Studio/assets/14124210/3a8bb976-8e8e-4b33-a4f6-4e963a76b929)

[SUSPECT2.zip](https://github.com/user-attachments/files/15604675/SUSPECT2.zip)

**Comment by GeorgRottensteiner** [comment]
From a glance it looks like you're using Palette Offset 1 (equals 16), but in C64Studio you're set to 0. Palette colors 16 to 31 are a gray scale.

**Comment by jakebullet70** [comment]
YEP!!!!!!!!!!!!!!!  

X16 docs are not clear.
--------------------------------------------------------------------------------------------------------------------
palette offset is the palette offset for the sprite. Range is 0-15 inclusive. This value is **multiplied** by 16 to determine the starting palette index.
--------------------------------------------------------------------------------------------------------------------

0 x 16 = 0
I will file a bug in the DOCS for the X16 program.

Closing.  Thanks!!!

**Comment by jakebullet70** [comment]
Now that I think about it....  0 is a number!!!!

**Comment by GeorgRottensteiner** [comment]
Glad to be of service. This issue lead me to finding lots of bugs in my CommanderX16 sample project.
And also I noticed I have no Commander X16 BASIC dialect file (and I'm sure I had one before).

**Comment by GeorgRottensteiner** [comment]
Nice :)

C64Studio also has a line number less mode, but I haven't checked in for Commander X16 for quite a while.
