### ISSUE TITLE
PetSCII table window is not poppung up anymore

### ISSUE THREAD

**Issue by jecepede** [GeorgRottensteiner/C64Studio#115]
Aloha !

Issue : 
---
The PetSCII table window is not poppung up anymore.

Reproduction : 
---
- Start C64Studio. (Empty or with solution/project does not matter)
- Click "Window"
- Check "[ ] PetSCII table"

The C64Studio application suddenly is not active anymore, 
you can tell from the title bar going light grey.
There is no PetSCII table in sight. It is not in C64Studio or on any other screen.

Workaround : 
---
After the C64Studio application is not active anymore, 
press [ ALT ] + [ SPACE ] and select "Change size". 
You can now, by dragging the mouse, get the window back.

System info : 
---
Windows : 10
Version : 7.8 .NET 3.5 & .NET 6.0-windows

.

Cheeeeeeeeers

Jecepede

**Comment by GeorgRottensteiner** [comment]
From the workaround, did you see the size of the window? Was it tiny or off screen?

I put a sanity check on startup that ought to ensure a minimum size of 50x50 pixel, but that seems to have not worked in your case.

**Comment by jecepede** [comment]
Hi,

Sorry for the late reply. 
The Window was completely off screen, even off the monitor.

For example, the monitor is 1920x1080  pixels, 
but the top let of the window could be at 2065x145.

.

Cheeeeeeeeers

Jecepede

**Comment by GeorgRottensteiner** [comment]
With release 7.9 tool window sanitation is used, any dialog totally off the visible area is moved to the top left edge as a workaround.
