### ISSUE TITLE
Char Screen Editor: exported assembly code with "" chars between each byte

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#116]
Studio 7.8

In the "Char Screen Editor", when I export my small level into assembly with Petscii style activated, I'll get many "" entries between each byte, for example:
`!pet "", $4F, "", $77, "", $77, "", $77, "", $77, "", $77` ...

In the screenshot you can see all my settings. 
When I deactivate "Prefer PetSCII", then I get the following (for me correct) output:
`!byte $4f,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$77,$50` ...

Maybe, I am wrong and those NULL items are correct, then ignore my bug report because I am new to the screen editor.

![Screenshot 2024-06-14 123404](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/1fc28808-011c-471a-8498-cc5f9cceef6a)

**Comment by GeorgRottensteiner** [comment]
Hmm, blanks would be fine, but empty is weird. Which mode did you set your char screen to? Generic Commodore, or is it using one of the Mega 65 16bit char modes? 
I see that in those cases the upper byte (which is usually zero) is wrongly exported as "".

**Comment by hkramer70** [comment]
I worked with the Mode "Commodore 40x25 HiRes" (see screenshot 2).
![Screenshot 2024-06-14 153813](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/d2114ada-8e09-4728-a8ee-13d08ea69217)

**Comment by GeorgRottensteiner** [comment]
Ah, got it. Stupid bug of mine, where I expected readable strings most of the time.

**Comment by GeorgRottensteiner** [comment]
Fixed with commit 6cf3364f4e51dfe968b59325fcdbae9bd286e4be.
Updated the WIP version at https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

**Comment by hkramer70** [comment]
Thanks for instant fixing :). The unnecessary "" entry is gone 👍.

But: Is that normal, that in "Prefer petscii" mode the colors won't be exported when selecting "Export Data" "characters, then colors"?

**Comment by GeorgRottensteiner** [comment]
Good question. I think it comes from the fact that this specific export is derived from the PRINT statement creator, where the colors are included in the statements.

I'll add the colors, they won't be !pet however, but !byte statements.

New WIP version is up (both issue 117 and 116 included)

**Comment by GeorgRottensteiner** [comment]
Closing this, if you feel it's wrong feel free to reopen
