### ISSUE TITLE
!media pseudo opcode won't export sprite data of SpritePad C64 Pro V3.52 sprite project file (.spd)

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#118]
Studio V7.8

I'm trying to export sprites from a SpritePad spd file directly into the assembly file with the !media pseudo opcode. But I'm not able to "see" those sprites.

In my SpritePad Pro project I have defined two sprites.
In the assembly code I'm trying to export them with the following code:

`sprNum !byte spriteBank/64, (spriteBank/64)+1

*=$2000
charset
!source "charset03.asm"

*=$3800
levelData
!source "level03.asm"

!align 63, 0
spriteBank
!media "Sprites.spd", sprite
`

I also tried out the "sprite" command with index/count and the "spritedata" command with index/count/offset/bytes.
But none of them works. Even if I set the "count" to 2 (because the project contains 2 sprites), the assembler won't assemble my source code and shows an error message: "Invalid sprite count 2".

Do I use that !media opcode wrongly?

**Comment by GeorgRottensteiner** [comment]
That's exactly how it's supposed to be used.

How big is your level data? Could it be that the sprites are put into the next VIC bank? (>= $4000) 
Remember the VIC can only use chars, screen and sprites inside on 16kB block.

**Comment by hkramer70** [comment]
No, I am lower than $4000. 

I rearranged that DATA block to make sure that I didn't go behind the scenes... (see screenshot). In the screenshot you can see, that the amount of bytes of the sprite project (!media) is set to only 64 bytes (see the assembler output left to the line #106).

You can see the sprites in the Spritepad project in the second screenshot. There are 3 and the first is a multicolor sprite.

The third screenshot shows the 3*64 bytes (as sprites) that is in RAM when it runs (the fourth picture shows the memory in $2800).

I hope the problem sits before my monitor :).


![Screenshot 2024-06-17 103448](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/cd9cfdae-5a18-46db-9b9a-9de4e1e5de84)

![Screenshot 2024-06-17 103754](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/524eb297-83c9-4fb7-b84f-775edb49c1bd)

![Screenshot 2024-06-17 103812](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/e7233d5a-dd64-43e6-8150-4122ab6bbe67)

![Screenshot 2024-06-17 103849](https://github.com/GeorgRottensteiner/C64Studio/assets/23117228/e2e6aba8-17d3-46b8-a874-e57082043695)

**Comment by hkramer70** [comment]
As I can see on the SpritePad Editors homepage, they changed the name of it from SpritePadPro to SpritePad C64 Pro. And it seems that they changed their project file format... :(. Is it possible that you are referencing the SpritePadPro up to Version 3.20 only?

**Comment by GeorgRottensteiner** [comment]
This could well be the issue. I can see the sprite is nearly there, just offset by a few bytes. 
Could you attach that .spd here? 
Unfortunately I didn't write down the version I've implemented this for.

**Comment by GeorgRottensteiner** [comment]
I managed to fix the import for version 2, 3 and 4 now. New WIP version is up.
I couldn't get my hands on a version 5, but it should work as I've got the documentation for its format.

Let me know if it fixes the problem with your Spritepad file.

**Comment by hkramer70** [comment]
[Sprites.zip](https://github.com/user-attachments/files/15872963/Sprites.zip)

**Comment by hkramer70** [comment]
Where can I find the WIP version?

**Comment by GeorgRottensteiner** [comment]
Ah, sorry, WIP version is always this link: https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

I'm so used to having that in my signature.

**Comment by hkramer70** [comment]
The WIP version (V7.8.8) reads the project file. At least, it shows the 192 byte for the 3 sprites of the SpritePadPro sprite file correctly. 
But there is still an issue with the first sprite (multicolor). But, who knows, maybe I didn't setup the MC mode on sprite #0 properly!? I will have more time at evening...

Thanks for your great support!!!

**Comment by hkramer70** [comment]
YES...the proplem sits in fornt of the monitor... I made a mistake on setting up the MC mode on sprite #0 :/

**Comment by GeorgRottensteiner** [comment]
Awesome, thanks for testing!
