### ISSUE TITLE
In Basic V7 kann (im Label Mode) ein Label nicht als Referenz für eine Zeilennummer verwendet werden

### ISSUE THREAD

**Issue by hkramer70** [GeorgRottensteiner/C64Studio#123]
C64Studio 7.8.16

Ich programmiere für den C128 mit Basic V7. In einer Zeile benötige ich für den [Collision-Befehl](https://www.c64-wiki.de/wiki/COLLISION) eine Zeilennummer, in die bei einer Sprite Kollision gesprungen werden soll.

Da ich im Label-Modus programmiere, kann ich keine Zeilennummer angeben. Folgende Zeile funktioniert mit einem Label allerdings leider nicht:

```
COLLISION 2, LABEL9000
```
 
Im Vice wird daraus:
```
?syntax error in 150
ready.
list 150

150 collision 2, dload9000
```

**Comment by GeorgRottensteiner** [comment]
Ah, never looked deeper into it. I need to expand the dialect file description to be able to define linenumbers for certain arguments.

**Comment by GeorgRottensteiner** [comment]
Fixed with commit 69689fb0fbfb865260f90432f97ebe4568172821
This also has updated dialect files.

The WIP version at https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip also has the fix.

**Comment by hkramer70** [comment]
Collision now works  fine with a label. Nice and thanks a lot :D.

There are three more commands: Trap, Resume and Restore.

**Comment by hkramer70** [comment]
I don't know if this is because of your fix of my issue or because of other changes you made. But now I get those build warnings in label mode:
```
132;W1003;G:\work\c64_128\Studio\Centi128\bresenkreis.bas;Referencing missing line number 2
23;W1003;G:\work\c64_128\Studio\Centi128\bresenkreis.bas;Referencing missing line number 24
22;W1003;G:\work\c64_128\Studio\Centi128\bresenkreis.bas;Referencing missing line number 0
21;W1003;G:\work\c64_128\Studio\Centi128\bresenkreis.bas;Referencing missing line number 39
20;W1003;G:\work\c64_128\Studio\Centi128\bresenkreis.bas;Referencing missing line number 0
```

They are not destructive. I can work with it. But I never saw them before.

**Comment by hkramer70** [comment]
[RetroCenti-main.zip](https://github.com/user-attachments/files/16324680/RetroCenti-main.zip)

**Comment by GeorgRottensteiner** [comment]
Yeah, I noticed that error I introduced. It's already fixed as well, I added all kind of numeric values as line number reference.
Added the other tree tokens, should work now. It might be, that RESTORE using a calculation starting with a number will be now mis-calculated, that seems like a pretty special case I need to treat specifically.

Updated the WIP version!

**Comment by hkramer70** [comment]
I tested all commands with labels in Studio V7.8.23 and they all work fine.
The errors / warnings are not printed anymore.

Issues seems to be solved... thanks 👍
