### ISSUE TITLE
Where's the multicolor checkbox?

### ISSUE THREAD

**Issue by Dart-Matter** [GeorgRottensteiner/C64Studio#125]
Where's the multicolor checkbox?

![image](https://github.com/user-attachments/assets/5631cfb9-0399-479f-a058-448fab5b32d0)

**Comment by GeorgRottensteiner** [comment]
There is no checkbox, as multicolor mode depends on the color value directly. Choose any Char Color >= 8 activates the multicolor mode:

![image](https://github.com/user-attachments/assets/e7689c2a-9a0f-4091-afad-4988304c29c5)

**Comment by Dart-Matter** [comment]
I see.  That is an unintuitive UI even when I understand how the hardware implementation works.  Seems like the multicolor checkbox was a better way to abstract that attribute.
