### ISSUE TITLE
Export to Assembly leaves the hex values in each line

### ISSUE THREAD

**Issue by hyphz** [GeorgRottensteiner/C64Studio#15]
Using Export to Assembly leaves the hex values for each line of assembler in the code. This means that the .asm file generated is invalid and has to be fixed up.

**Comment by GeorgRottensteiner** [comment]
Good catch. I should've noticed earlier, will be fixed asap!

**Comment by GeorgRottensteiner** [comment]
Fixed with Commit #a4ee882e, thanks!
