### ISSUE TITLE
If opcodes contains a forward reference to a zero page address, wrong opcode version is used

### ISSUE THREAD

**Issue by hyphz** [GeorgRottensteiner/C64Studio#17]
`variable = $02
sta variable`

assembles the sta as $85. But

`sta variable
variable = $02`

assembles the sta as $8D.

**Comment by GeorgRottensteiner** [comment]
That one's actually by design. The assembler needs to know the size of an opcode to go forward. If the value is not known beforehand it has to play safe.

If you want to force a certain opcode size you can add +1 or +2 to an opcode to force ZP or non ZP:

sta+1 variable
sta+2 variable
