### ISSUE TITLE
Search .word -> !word crashes

### ISSUE THREAD

**Issue by daitangio** [GeorgRottensteiner/C64Studio#18]
On windows 10, I tried to do a search and replace of ".word" into "!word" on a file and the IDE showed a C# Crash Report.
Also the editor was cleared

**Comment by GeorgRottensteiner** [comment]
Dang, that's one particular error I'm trying to track down, but can't for my life reproduce. Do you have any specific file that you can use to reproduce that bug?

**Comment by daitangio** [comment]
Try the attached one

**Comment by GeorgRottensteiner** [comment]
Sorry, I don't see an attachment on this issue. If you want you can mail it to me directly (georg@georg-rottensteiner.de)

Thanks!

**Comment by GeorgRottensteiner** [comment]
Thanks for the file! I managed to run into one crash and added a quick avoidance hack. I have to investigate the cause further, but for now this ought to help (commit #a8179c9f)

**Comment by GeorgRottensteiner** [comment]
Did the crash still appear?

**Comment by daitangio** [comment]
Not yet tested, sorry.

**Comment by GeorgRottensteiner** [comment]
Assumed as fixed.
