### ISSUE TITLE
No Keybindings for editors?

### ISSUE THREAD

**Issue by AndyHOvine** [GeorgRottensteiner/C64Studio#19]
Could a future version get some keybindings for the editors, for example the sprite editor would benefit from bindings for:

Select colour (background, Multicolor 1. 2 and sprite color)
Go to next and previous sprite
Shift sprites up/down/left/right
Mirror and flip

Similar for charset, text screen and other editors?

**Comment by GeorgRottensteiner** [comment]
It's on the TODO list as of right now.

**Comment by AndyHOvine** [comment]
Fantastic. Loving the flexibility of the editors and keyboard shortcuts will make it even easier.

**Comment by GeorgRottensteiner** [comment]
First commit is in, with key commands for charset and sprite editor (for now)

**Comment by AndyHOvine** [comment]
Wonderful, look forward to trying it out.  Loving the sprite editor and this will make it easier to use :)

**Comment by GeorgRottensteiner** [comment]
The 6.1 release contains the most important key bindings now, you may have to set the bindings.

**Comment by AndyHOvine** [comment]
Working great, thank you.  So quick to edit now.  Have found one bug, will raise separately.
