### ISSUE TITLE
SocketException when Debugging

### ISSUE THREAD

**Issue by tingtron** [GeorgRottensteiner/C64Studio#20]
I am using C64Studio 6.1 and when attempting to Debug, getting the following error:
```
RemoteDebugger.Connected Exception:System.Net.Sockets.SocketException:
  No connection could be made because the target machine actively refused it 127.0.0.1:6510
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at C64Studio.VICERemoteDebugger.Connected(IAsyncResult iar)
```
The error  appears in the Output panel before Vice window is shown.

I was wondering, if it would help to add a (configurable) wait and/or timeout before attempting to connect to the debug socket.

**Comment by GeorgRottensteiner** [comment]
Which VICE version do you use? There is sort of a timeout during startup of the emulator, but the console window of the GTK version nicely grabs the input queue.
I'll double check with the GTK version and try to add a timeout for the socket as well.

However make sure the local firewall is not in between on port 6510.

**Comment by GeorgRottensteiner** [comment]
I've tested with GTK VICE and added a 10 repeated connection attempts with a delay of 1 second. That's long enough to work on my slug of a machine.
Added with commit #9872c8

**Comment by tingtron** [comment]
Really appreciate a quick look into it.

I am using GTK3VICE-3.3-win32-r35896. I tried both x64.exe and x64sc.exe (cycle accurate).

One more comment: the error (failed connection) happens intermittently. It looks like it depends on a running instance of the IDE - if it succeeds once, it will continue to succeed until closing IDE. If a new IDE session failed once, it will continue failing. So this intermittency suggested the idea of timeout as you did. It also excludes the potential on Firewall or Loopback adapter issues.

Thank you for getting the fix in. I'll test it out when available and let you know.
