### ISSUE TITLE
Rotate sprite loses some pixels in multi-colour mode

### ISSUE THREAD

**Issue by AndyHOvine** [GeorgRottensteiner/C64Studio#21]
When I rotate a multi-colour sprites 90 degrees I am losing some pixels.  Hires mode appears to work fine though.

**Comment by KrzysztofJeszke** [comment]
It's not the fault of the software but the commodore limitations. Hi-Res sprites are 24x21 pixels. But the multi-color sprites are 12x21 and this is where losing pixels starts. Since you're probably using a sprite that's not in a 12x12 area you will lose pixels

**Comment by GeorgRottensteiner** [comment]
Sorry for the late reply, I must have missed the notification for this issue. As KrzysztofJeszke said, you're obviously losing precision. C64Studio works in the limitations of the C64.

**Comment by AndyHOvine** [comment]
Hi, yes I realise that and understand. I observed bits missing like it was trying to match the colour bit pairs and understandably looses precision. I would have to go back to check exactly what I saw as it was some time ago and try to explain it better. :)
