### ISSUE TITLE
Keybindings for selecting colour to draw with

### ISSUE THREAD

**Issue by AndyHOvine** [GeorgRottensteiner/C64Studio#22]
The new key bindings for the Custom Color, Multi Color 1 and Multi Color 2 are changing the colour index (selecting the next colour).

Would it be possible to add bindings to select Custom Color, Multi Color 1 and Multi Color 2 (ie: as if I clicked on their radio button) so I can draw with that colour?

**Comment by GeorgRottensteiner** [comment]
Apologies for the late reply, I totally missed your issues.
They have been added with commit 81bf5f17.

**Comment by AndyHOvine** [comment]
Brilliant:)
