### ISSUE TITLE
Suggestion: Turn off automatic switching of input modes in BASIC mode

### ISSUE THREAD

**Issue by rabejens** [GeorgRottensteiner/C64Studio#29]
When I am in BASIC mode, entering something like `10 PRINT"` it goes into this special input mode like on a real C64/VIC20, but a lot of other editing functions are then not correctly usable. I always have to click the buttons on the upper side of the input window to reset editing mode. There should be key combinations to do this, or a mode which turns off switching input modes.

**Comment by GeorgRottensteiner** [comment]
Good idea!
Added as general setting, defaulting to true, with commit #2ce28275!

**Comment by GeorgRottensteiner** [comment]
Closing since it's fixed
