### ISSUE TITLE
Suggestion: Strip REMs from a BASIC program

### ISSUE THREAD

**Issue by rabejens** [GeorgRottensteiner/C64Studio#30]
Especially when writing BASIC programs for the VIC20, you probably want to save each and every tiny byte. REMs help finding your way through your code, but they eat up precious space. I suggest there should be an option that strips all REMs when building the .prg file.

**Comment by GeorgRottensteiner** [comment]
Sounds like a sensible option. I was actually thinking to even include non BASIC comments, that are always stripped (something like // without line numbers)

**Comment by rabejens** [comment]
I thought of that as well. That'd be even better. They could use the non-C64 font.

**Comment by GeorgRottensteiner** [comment]
A strip-REM-commands option is included, the other variant not (yet)
