### ISSUE TITLE
New Feature: Vic 20 Support

### ISSUE THREAD

**Issue by AndyHOvine** [GeorgRottensteiner/C64Studio#31]
Wondering if Vic 20 support in C64Studio could be a thing?

Memory options is likely to be the initial part to address (unexpanded, 3k, 8k+) but otherwise lots of similarities on a cut-down scale.

Also the built in debugger support would be cool (it currently falls back to the Vice monitor if point to xvic.exe)

**Comment by GeorgRottensteiner** [comment]
Might be doable. One problem is that I don't know many details. The assembler itself would be the simpler part, but charset etc. editors need matching options.
C64Studio checks whether the called filename starts with "x64". If it's not, it assumes not VICE and omits the remote monitor. That should be easy to fix.
Would you dare to test? ;)

**Comment by AndyHOvine** [comment]
Absolutely, throw anything my way :)  

I think the character and screen editors can be used as they are.  The differences are minor although any support you can add for the Vic would be a bonus.

Some comparisons key highlights that might be applicable:

- C64 and Vic hi-res characters are the same
- The Vic can only use the first 8 colours (bits 0-3, bit 4 is the multicolour flag)
- Vic 20 multi-colour characters are very similar with a character colour, an Aux (MC1) and Border (MC2) colours.
- The Bit pairing mask for multi-colour encoding is slightly different. 
- The top 8 multi-colours have differences
- The Vic 20 has an inverse colour mode and a double height character mode
- The Vic 20 does not have the ECM or bitmap modes (although the latter can be simulated)
- The Vic 20 screen default is 22 x 23 so the screen character editor can be used pretty much as-is.  Width and height can be shrunk/enlarged by any visible amount.

Any support for the above are not essential but would be a bonus.  The two immediate features that would be a big help would be the integrated debugger and an easy way to pass the desired memory expansion option on the command line.

**Comment by GeorgRottensteiner** [comment]
What exactly does not work with the debugger? I fired up a simple assembly and was able to debug step through it. I cloned a tool entry of VICE and replaced x64.exe by xvic.exe. 

The assembly:
* = $1001

!basic

          lda #1
          sta $1400
          rts

**Comment by AndyHOvine** [comment]
This is what I have:
![image](https://user-images.githubusercontent.com/710401/86567924-033a2b00-bf64-11ea-99a9-c1389c09ad96.png)

I tried it with this test program with a breakpoint set:
![image](https://user-images.githubusercontent.com/710401/86567397-35975880-bf63-11ea-8e6d-24ac19aada11.png)

xvic starts and the breakpoint is hit in the VICE monitor.  

![image](https://user-images.githubusercontent.com/710401/86567613-8ad36a00-bf63-11ea-9365-0aa11a4c11eb.png)

When I do this with an C64 program, the breakpoint is hit and returns to C64Studio to debug, however, with this Vic set up C64Studio remains unaware and the step button (for example) is not functional:
![image](https://user-images.githubusercontent.com/710401/86567760-ca01bb00-bf63-11ea-90fd-90c4bc6e0d90.png)

I'll grab a newer version of VICE to test as I'm on 3.1 at the moment ( the last good Windows version ;-p ).

**Comment by AndyHOvine** [comment]
Same with latest VICE.
![image](https://user-images.githubusercontent.com/710401/86568856-6c6e6e00-bf65-11ea-87d3-213f6596d4c7.png)

**Comment by GeorgRottensteiner** [comment]
Ah, I checked with VICE 2.4.  Also works with 3.4 for me. 
Is there a message in the output display regarding debugger connection failed? Either your PC is so fast and the location is passed before the remote monitor even connects; or the debugger connection isn't even opened at all.

**Comment by AndyHOvine** [comment]
Figured it out.  I thought I'd updated recently but I was still on V 6.1.  Installed 6.4 and the debugger stopped working initially.  Created a new project and copied over the asm file and debugging is now working perfectly.

**Comment by GeorgRottensteiner** [comment]
Phew! Thanks for checking!

**Comment by GeorgRottensteiner** [comment]
Closing since it works.
