### ISSUE TITLE
User interface text appears blurry on Windows 10

### ISSUE THREAD

**Issue by GiovanniDicanio** [GeorgRottensteiner/C64Studio#32]
I ran the program under Windows 10, and the UI text appears blurry. This degrades the general UI experience. It would be great if you could fix that, and make the text crisp as one would expect from ordinary Windows applications.

**Comment by GeorgRottensteiner** [comment]
I develop on Windows 10, and don't have the problem. Did you change your DPI settings from the default maybe?

**Comment by GiovanniDicanio** [comment]
I haven't changed any DPI settings manually. I just use defaults.

**Comment by GeorgRottensteiner** [comment]
Can you attach a screenshot, so I can take a look perhaps?

**Comment by GiovanniDicanio** [comment]
![image](https://user-images.githubusercontent.com/4692631/98672819-afe34980-2356-11eb-8f6c-a8199d372c43.png)

**Comment by GeorgRottensteiner** [comment]
Thanks! That's definetively scaled somehow, I see what I can come up with.

**Comment by GeorgRottensteiner** [comment]
I found something that might help. Before I go and modify all dialogs, could you please download the WIP version from https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip and look?

I modified the main window and the about dialog. 

If that change works I'll apply it to all forms.

**Comment by GiovanniDicanio** [comment]
I downloaded the new version, and now the text is crispy clear! Thanks for your quick fix!

As a side not, could it be possible to change the font size based on user preference? I would love to be able to set a larger font, which would be more readable to me.

In any case, the text is now crisp.

![image](https://user-images.githubusercontent.com/4692631/98724119-8ac0fc00-2393-11eb-8092-a576d9ace37d.png)

**Comment by GeorgRottensteiner** [comment]
Great to know, thanks! I modified all potential dialogs with that change, commit 121d66a.

I also uploaded the new build in the webmisc link above. Thanks for checking!
