### ISSUE TITLE
Non initialized memory NOT being 0x00

### ISSUE THREAD

**Issue by mwedmark** [GeorgRottensteiner/C64Studio#33]
If Adding something like this to the end of a program:

*=$1f00+2000

It looks like only the memory from the first term ($1f00 gets initlialized to 0x00) and the rest ( from $1f00 and forward) gets some kind of garble..

**Comment by GeorgRottensteiner** [comment]
Is there anything after this line? 
What is before that line?

That line by itself only sets the start address of anything after it. If there was something before any memory between that location and $3f00 should be filled with zeroes (is that what isn't happening?)

**Comment by mwedmark** [comment]
Correct! I just needed a big lump of memory at the end for tests.  I
noticed that i got that without actually having anything (no file and no
data) there but 0x00 are only added automatically to data between end of
program and to start of first  part of statement.

Den sön 13 dec. 2020 14:34Georg Rottensteiner <notifications@github.com>
skrev:

**Comment by GeorgRottensteiner** [comment]
I have a hunch what might cause this.

I added a detection of unused sections for the virtual labels. Basically C64Studio detects that the section at $1F00 + $2000 has no content and discards it.
I’ll see to add a fix for that. 

Thanks!

**Comment by mwedmark** [comment]
Ah sorry, It's a bug in my Hexviewer (in Notepad++). 
But for example 
*=$2500+10

gives a file with size: 7 435 bytes ( $1D0B)

There's something weird going on..

**Comment by GeorgRottensteiner** [comment]
I think I've fixed it with commit fa8291a6. Can you please try with the WIP build unter https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip?

**Comment by mwedmark** [comment]
Or actually sorry again. because of two labels, one from the original program and one from the data I think I'm wrong!

Because the first * is $0801 and last * is $250A the total size if just between these:

$250A - $0801 = 1D09 and adding the last lda#00 instruction => **$1D0B**

Sorry for the inconvenience!! Such a GREAT tool, especially when using it with my new cart Kung Fu Flash. I've added a "Download to C64" which works 100%.

Here's the example:

!to "sidasm.prg", cbm
!cpu 6510
!ct pet

;SIDLoad = $11c0          ; found in the 125th/126th byte of the PSID header (7C bytes in)
;!!!NOTE!!! this is a C64 load address and therefore in low/high order.
;SIDInit = $11c0          ; found in the 11th/12th byte of the PSID header (10 bytes in)
;SIDUpdate = $11e7        ; found in the 13th/14th byte of the PSID header (12 bytes in)
;PSIDHeaderSize = $7c     ; v2 ie size found at the 8th byte of the PSID header (7 bytes in)

TrackIndex = 0           ; check 15th/16th byte to see how many tracks are
                         ; in the file and hence how high you can
                         ; make this value.

ZPProcessorPortDDR        = $00
ProcessorPortDDRDefault   = %101111
ZPProcessorPort           = $01
ProcessorPortAllRAMWithIO = %100101

CIA1InterruptControl      = $dc0d
CIA2InterruptControl      = $dd0d

VIC2ScreenControlV  = $d011
VIC2Raster          = $d012
VIC2InteruptStatus  = $d019
VIC2InteruptControl = $d01a
VIC2BorderColour    = $d020
VIC2ScreenColour    = $d021

VIC2Colour_White = 1
VIC2Colour_LBlue = $e

KERNALIRQServiceRoutineLo = $fffe
KERNALIRQServiceRoutineHi = $ffff

!macro AckRasterIRQ {
   lda #1
   sta VIC2InteruptStatus
}

!macro AckAllIRQs {
   lda CIA1InterruptControl
   lda CIA2InterruptControl
   lda #$ff
   sta VIC2InteruptStatus
}

*= $0801
!byte $0b,$08,$01,$00,$9e      ; Line 1 SYS2061
!convtab pet
!tx "2061"
!byte $00,$00,$00

!zn
; EXTRA CODE HERE

!align 1, 0 ; wait for even address
SIDLoadAddr !word
SIDInitAddr !word
SIDUpdateAddr !word

*= $250A ;$1f00+2000 ;1530
StartOfSID
lda #00

**Comment by GeorgRottensteiner** [comment]
I think in that case the fix should help with that issue. Have you tried it?

Hint: The BASIC start line can be shortened to  

* = $0801
!basic

!zn

**Comment by mwedmark** [comment]
Thanks for the tip. I'll check that. Sorry to say, I have no known bug to test. Everything was User faults. But thanks to your quick support I've found my current bug. I'm trying to add SID player to Kung Fu Flash cartridge. Combination of C64 assembler and STM32 C code.
