### ISSUE TITLE
Debugging does not work with latest WinVICE version

### ISSUE THREAD

**Issue by derryx** [GeorgRottensteiner/C64Studio#34]
Debugging does not work with WinVICE version 6.5 (64bit). It seems not to get a connection.

C64Studio version is 6.6 on Windows 10.

**Comment by GeorgRottensteiner** [comment]
I see; you're using the old interface I guess.

Looks like VICE has a problem with labels set to $ffffffff, which spawn error messages. Which in turn confuse C64Studio. I'm on it, thanks!

**Comment by GeorgRottensteiner** [comment]
Ideally you should use the binary interface starting with VICE 3.4. They unfortunately removed a method in the old interface which I now have to detect first.

**Comment by GeorgRottensteiner** [comment]
I avoid sending duplicate labels, and out of bounds labels to VICE now; also the old binary mem dump is removed if GTK is detected. Fixed with commit f971ae3

For a WIP build you can go to https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

Thanks for the info!

**Comment by derryx** [comment]
I can confirm that the WIP build works. Thanks a lot!

Would it be possible to debug in the emulator for the C128 as well? I have checked that the binary interface is enabled for the monitor. This is something that does not work currently.

**Comment by GeorgRottensteiner** [comment]
That's something I have to look into. I just noticed it didn't work. Could be something with the 2 memory banks. Or my default initial breakpoint set at $a871.

**Comment by derryx** [comment]
I would close this ticket here and open a feature request. Again thanks a lot for the quick response!
