### ISSUE TITLE
win10 and a charset editor problem

### ISSUE THREAD

**Issue by theenemy-thd** [GeorgRottensteiner/C64Studio#36]
seems the charset editor when selecting chars to edit has an issue when selecting which char to edit.  When edited it doesn't to seem to show the edits as well. if you look at the attached jpeg you will see selecting the chars is just weird and that the screen to display is tiny
![charissue](https://user-images.githubusercontent.com/78659007/107126538-6ef0c780-68a8-11eb-8a05-c25ce2b40891.jpg)
 :( running 6.6 on window 10.

**Comment by GeorgRottensteiner** [comment]
Ouch, that's a non-standard DPI issue. 

That's something I have to address with a bigger rewrite. Thanks for the screenshot!

**Comment by theenemy-thd** [comment]
seems it was an update to win 10 on my home laptop as the work pc doesnt have the issue, yet :D but i do see it wants to update windows lol

**Comment by GeorgRottensteiner** [comment]
It's a scaling issue, I'm in the process of working over those controls/dialogs to fix these. It's just will take a bit to do.

**Comment by GeorgRottensteiner** [comment]
Just uploaded a preliminary version (binary and source) which fixes pretty much all scaling issue. There are still some smaller things, but the worst should be gone with commit 9ffbca54.
