### ISSUE TITLE
64tass/tasm support

### ISSUE THREAD

**Issue by theenemy-thd** [GeorgRottensteiner/C64Studio#40]
while im posting .... any chance you can support c64tass tasm syntax/pseudo commands please ... pretty please with cherries on top :D

wishful thinking

**Comment by GeorgRottensteiner** [comment]
Sure thing! Do you have any source files I can prey upon?

You wouldn't perchance know the binary format of TASM? I tried to dissect it but it's really really weird.

**Comment by GeorgRottensteiner** [comment]
TASM/64tass support has been greatly enhanced with 7.6. If you still find let me know.

**Comment by theenemy-thd** [comment]
many thanks for the info, i will try it out
    On Sunday, 29 October 2023 at 18:18:19 GMT, Georg Rottensteiner ***@***.***> wrote:  
 
 


TASM/64tass support has been greatly enhanced with 7.6. If you still find issues let me know.

**Comment by theenemy-thd** [comment]
there are still many issues. 
1. the closing of the if command .if and closing the if with .fi doesnt work.2.. .else isnt supported3.labels dont seem to be allowed on a line for example:

TRAINR:    LDA #$00
4. 64tass allows you to branch and jmp as per the following example:
    lda $0007    beq ++                ;this will jump to line "jmp $2000"    sta $0008    cmp #$0009    beq +                   ;this will jump to line "RTS"    sta $0009+  RTS
+  jmp $2000
this is the same using the - symbol to branch and jump backwards
5. disablehigh: =*+$1 isnt allowed ... this will take the position in memory of where the label is and add the $1 to it .. this could be any number to shift forward or    say using disablehigh: =*-$1 will shift it back then that label can be used later. maybe the example below will explain it better.

inc disbalehigh                    ;this will make the line below LDA #$01
disablehigh: =*+$1                  LDA #$00    On Sunday, 29 October 2023 at 18:18:19 GMT, Georg Rottensteiner ***@***.***> wrote:  
 
 


TASM/64tass support has been greatly enhanced with 7.6. If you still find issues let me know.

**Comment by GeorgRottensteiner** [comment]
Ah, more issues than I hoped. The ++ will be fun. I'll try to fix up these issues first.
e.g. = * + $1 ought to work (it does in other modes), probably an issue with the label in front that I'm doing wrong.

Will look into it, thanks!

**Comment by GeorgRottensteiner** [comment]
Fixed .if, .else, .fi, labels followed by : (which caused the other issues).

Not yet fixed: The accumulated +/- labels, that needs some special treatment. Uploaded a new WIP version for this

**Comment by theenemy-thd** [comment]
Wow! Quick work... looking forward to + /- branch/jmp issue being sorted

**Comment by GeorgRottensteiner** [comment]
Added the stacked +/- functionality, WIP version is updated. Let's see what I've broken and what the next issues are :)

**Comment by GeorgRottensteiner** [comment]
If you find new issues feel free to reopen, closing this for now.
