### ISSUE TITLE
operator precedence - modulus

### ISSUE THREAD

**Issue by mrj001** [GeorgRottensteiner/C64Studio#41]
The following line assembles in acme assembler.
`!byte run/1000 % 10 + '0'`
However, it produces this error in C64 Studio:
> Cannot evaluate expression run/1000 % 10 +'0'

This is because the modulus operator is higher precedence than division.  In most languages, division and modulus have the same precedence and are evaluated left to right.  This allows the above expression to work.

Is this precedence (modulus before division) correct?

There's an easy work-around, of course:
`!byte (run/1000) % 10 + '0'`

**Comment by GeorgRottensteiner** [comment]
Since I strive to be 100% compatible with ACME (which I know I'm not), I fixed the operator prio for modulus to match division. Fixed with commit 530df9fa.
I've uploaded a preview version to https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip
