### ISSUE TITLE
Add Breakpoint - not added to source window.

### ISSUE THREAD

**Issue by mrj001** [GeorgRottensteiner/C64Studio#46]
When clicking Add in the Debug Breakpoints window, the breakpoint is not added to the source window. 

The source window is showing the addresses for the instructions.  Even when the debugger is started, the breakpoint is not added to the window.  However, it does get hit.

I'm looking into this, but don't yet have a pull request.

**Comment by GeorgRottensteiner** [comment]
My breakpoint managing code is just ugly. Anyhow, worked the missing part inside. Breakpoints are now associated with a file when the address is found inside (Commit a26091b7)
