### ISSUE TITLE
Moving watched addresses may result in OutOfRangeException

### ISSUE THREAD

**Issue by pizza666** [GeorgRottensteiner/C64Studio#47]
Moving watched addresses during debugging may result in OutOfRangeException

![image](https://user-images.githubusercontent.com/28303235/118468364-f8fcc780-b704-11eb-99df-5d0e33d329f4.png)

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: Der Index muss sich innerhalb der Listenbegrenzung befinden.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.Generic.List`1.Insert(Int32 index, T item)
   bei C64Studio.DebugWatch.moveDownToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by GeorgRottensteiner** [comment]
I found a bug when using different projects in a solution regarding this. Are you using a setup like this?

**Comment by GeorgRottensteiner** [comment]
Made the watches per project now, so there shouldn't be a mismatch anymore. Potentially fixed with commit e9712159
