### ISSUE TITLE
Breakpoint disappeared

### ISSUE THREAD

**Issue by mrj001** [GeorgRottensteiner/C64Studio#49]
This was in Normal mode; I didn't try in Debugging Broken.

I clicked in the left hand edge to set a breakpoint on an instruction.

The breakpoint appeared in both the code window and the Breakpoints window.

I then deleted the line above the breakpoint.  This was a comment.  The breakpoint disappeared from both the source window and the Breakpoints Window.  I was able to reset it by clicking in the left margin of the source window.

**Comment by GeorgRottensteiner** [comment]
I see the breakpoint disappears when you select the line above, and the lower end of the selection (ie. the cursor) is at the start of the line with the breakpoint. 
I usually delete lines with Ctrl-Y (Delete line shortcut), where this doesn't happen.
Will be fixed!

**Comment by GeorgRottensteiner** [comment]
Oh boy. The text change events of FastColoredTextBox are unusable for this. It worked before by sheer luck. I need to add new events to the control to properly handle the breakpoint updates.

**Comment by GeorgRottensteiner** [comment]
Hopefully finally fixed with commit 65eb9b2d
