### ISSUE TITLE
still have this weird issue

### ISSUE THREAD

**Issue by theenemy-thd** [GeorgRottensteiner/C64Studio#54]
> Uploaded the fixed version to the usual link: https://www.georg-rottensteiner.de/files/C64StudioRelease.zip

only just tried this and still having the same problem :(

errors with unused label !text and !binary

Edit: think i have then found an additional bug. see attached pic, left works with below the first set of !text remd out, the right shows if then under with *=$xxxx and then !text the error comes back.

![bug](https://user-images.githubusercontent.com/78659007/135713320-994bb2aa-88d0-4d98-9205-1f4bb7788606.png)

_Originally posted by @theenemy-thd in https://github.com/GeorgRottensteiner/C64Studio/issues/39#issuecomment-932731384_

**Comment by GeorgRottensteiner** [comment]
I completely overlooked this issue, I'm so sorry. Could you send me those particular !text blocks with the problem? There must be something else triggering the issue.

**Comment by GeorgRottensteiner** [comment]
The code has been changed quite a bit, and I haven't heard back (sorry for the total too late reply back then).
Feel free to reopen!
