### ISSUE TITLE
Watch entries cannot be deleted permanently

### ISSUE THREAD

**Issue by komposter64** [GeorgRottensteiner/C64Studio#55]
C64 Studion 6.9, while debugging assembly files.

Once entries have been added to the watch window, they cannot be deleted permanently. You can remove entries temporarily during a debug session, but changes aren't saved, when the session ends. Entries reappear when restarting the debug session or after saving and quitting out of C64 Studio and reopening the project. 

I took a brief look at the source code of C64 Studio and it seems like watch entries are transferred from the project settings to the watch window, but changes in the watch window aren't transferred back to the project settings. This seems to be due to a missing 
```m_CurrentProject?.Settings.WatchEntries.Remove(Watch);``` in ```MainForm.RemoveWatchEntry()```.

**Comment by GeorgRottensteiner** [comment]
Good catch! I do remember wondering about multiplying watch entries, this seems to have solved that. Thanks!

Fixed with commit #2f3feaa7

**Comment by komposter64** [comment]
No problem. Thanks for the quick response. If I ever figure out how git works, I can provide fixes more directly ;)
