### ISSUE TITLE
!TRACE does not output address value, but acts as a breakpoint

### ISSUE THREAD

**Issue by tingtron** [GeorgRottensteiner/C64Studio#59]
`!TRACE <Expression>` is documented as "expression is evaluated ... as address and ... the value is written to the output window".

But nothing is printed in the output window of either C64 Studio or VICE terminal.
Instead, it act as an extra breakpoint.

Note: it is translated in the `-moncommands` file as `break exec <trace location>`

**Comment by GeorgRottensteiner** [comment]
Nice, that one was pretty much broken. Fixed with commit #80fc3e3f

Info: !trace does use "break exec" in the background. It's utterly slow as every hit will require a short break, a small mem dump and resume. It's not really usable for real time debugging.
