### ISSUE TITLE
Latest versions of WinVICE don't seem to work in combination with C64 Studio

### ISSUE THREAD

**Issue by cdacunha71** [GeorgRottensteiner/C64Studio#60]
I can't get latest versions (GTk or SDL) to work. When I try to build an run I get an exit code 1. Tried several versions but all show give the same error.

**Comment by GeorgRottensteiner** [comment]
Unfortunately the VICE guys changed the arguments. When wrong ones are passed, there's no message whatsoever, it just won't start up.

In File->Preferences->Tools change these settings for the emulator:

In "True Drive On" and "True Drive off" replace "truedrive" with "drive8truedrive" and "virtualdev" with "virtualdev8"

**Comment by cdacunha71** [comment]
Thanks Georg, this solved the issue
