### ISSUE TITLE
GTK3VICE-3.6.1-win64 not working

### ISSUE THREAD

**Issue by pizza666** [GeorgRottensteiner/C64Studio#62]
I updated my GTK3VICE-3.5 to 3.6.1 and it seems its not working. Doesn't even bring up a VICE window or writes anything to the the vice log.
Is 3.6.1 already supported with 7.1?

**Comment by GeorgRottensteiner** [comment]
With VICE 3.6 the developers unfortunately changed the runtime arguments. In File->Preferences->Tools please change the arguments for "Truedrive off" to "+drive8truedrive -virtualdev8" and for "Truedrive on" to "-drive8truedrive +virtualdev8"

Unfortunately there's no way to detect the VICE version properly.

If that doesn't help please let me know.

**Comment by pizza666** [comment]
Ok, that worked fine thanks!

**Comment by GeorgRottensteiner** [comment]
Glad to be of service!

**Comment by empathicqubit** [comment]
@GeorgRottensteiner The binary monitor has a command to detect the version. I ran into some problems with some arguments changing around too:

https://github.com/empathicqubit/vscode-cc65-debugger/blob/master/src/dbg/vice-grip.ts#L91

https://github.com/empathicqubit/vscode-cc65-debugger/blob/master/src/dbg/vice-grip.ts#L167

https://vice-emu.sourceforge.io/vice_13.html#SEC324

**Comment by GeorgRottensteiner** [comment]
Yeah, that's a nice addition. Still a bit cumbersome to start up VICE to check the running version. I think I placed a request to add a simple -version argument switch.

**Comment by empathicqubit** [comment]
There is a libretro version of VICE, I think, but I have no idea if it's recent or would give you access to what you need

I'll try to see if I could add the version switch. Would definitely be useful.

**Comment by empathicqubit** [comment]
I guess it's already there: 

```
r41727 | gpz | 2022-02-03 17:40:02 +0100 (Thu, 03. Feb 2022) | 1 Zeile

added -version cmdline option to the emulators
```

**Comment by GeorgRottensteiner** [comment]
Good to know, thanks!
