### ISSUE TITLE
System.NullReferenceException when opening preferences in 7.1

### ISSUE THREAD

**Issue by pizza666** [GeorgRottensteiner/C64Studio#63]
I get a System.NullReferenceException when opening the preferences in 7.1
I already tried to remove the settings.dat and let C64STudio create a new one but still the same.
Its happing on:
https://github.com/GeorgRottensteiner/C64Studio/blob/aaf2d8614a24df809a6c3784bf4a7cf3ab31e0aa/C64Studio/Dialogs/Settings.cs#L190

**Comment by GeorgRottensteiner** [comment]
I found that one bug directly after releasing the first version 7.1. 
Could you please re-download the release from the usual link, that one should be fixed already. It failed at a new WIP function for relocation files.
