### ISSUE TITLE
Implicit converting from sta (address),x to sta adress,x without warning

### ISSUE THREAD

**Issue by snoopy78** [GeorgRottensteiner/C64Studio#64]
In https://www.retro-programming.de/programming/assembler/asm-grundlagen/debuggen/ there is a sample, where sta (address),y is used. As beginner, I tried to use the x register: sta (address),x and the sample was generated, but not working. With the debugger I found out, that the mnemonic was implicitly converted to sta address,x what should not be done. The studio should generate an error like "not implemented use of mnemonic" or something else or "not implemented use of mnemonic -> converted to xy" or something like this.

**Comment by GeorgRottensteiner** [comment]
I think that's a proper request. C64Studio tries to be helpful, but that maybe is too much.
ACME pops an error message (Illegal combination of command and addressing mode).

I'll adjust accordingly!

**Comment by snoopy78** [comment]
I used the C64 CPU with start at $801 like in the example with sta ($fb),x from the zeropage (maybe this was the problem).

Hmm, that's strange. Now I get the same error message, which I don't got when I tried the example at the first time. You don't have fixed this between 7.0.1 and 7.1? I haven't read something for this error in the release notes.

**Comment by GeorgRottensteiner** [comment]
Ah, could be that one got fixed. I remember there being that particular issue. Sometimes checkins contain more than one fixes.
So I'll close this one then.

Thanks!
