### ISSUE TITLE
!scr is not used the same as in ACME

### ISSUE THREAD

**Issue by snoopy78** [GeorgRottensteiner/C64Studio#65]
Hi Georg

I'm not sure, if this is an error or only "other behavior". In the same example (https://www.retro-programming.de/programming/assembler/asm-grundlagen/debuggen/) the directive !src is used (more or less at the end of the page).
With this, the code should not be interpreted as PETSCII like !text then with the ones from the CHAR-ROM.

What do you think about this?

**Comment by GeorgRottensteiner** [comment]
C64Studio is trying to mimic ACMEs behaviour, so !scr, !pet and !text are all behaving exactly like ACME 
(Unless I have an error there)

!SCR will insert screen codes, while !PET works like !TEXT, but reverses character casing. !RAW inserts bytes untouched.

Note however !text can be influenced by !convtab/!ct

**Comment by snoopy78** [comment]
OK. Works in 7.1 too. I thought, I have tested it and it did not work, but now, the !scr works smooth with the arguments "a","b"...
