### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by chrisgleissner** [GeorgRottensteiner/C64Studio#71]
Hi,

I tried to enable dark mode in C64 Studio since the current setup hurts my eyes. In the last few years, most IDEs started offering dark mode support.

I see that a few releases ago, C64 Studio added the ability to define custom element foregrounds and backgrounds (Menu / Preferences / Colors). However, even after spending quite some time, I was unable to achieve a satisfactory setup. Basically, some parts of the IDE still show a bright background.

I see that there is an "Export here" and "Import here" button in that dialog. Would it be possible to define dark mode settings and then export them for download via GitHub? This could then be expanded to offer an "Enable Dark Mode" button to the left of the "Set Defaults" button on the Colors panel. 

Just a thought. I would really love to use C64 Studio as it is such a great tool, but the lack of a workable dark mode forces me to use Visual Studio Code instead. 

Thanks
Christian

**Comment by GeorgRottensteiner** [comment]
Everything's possible. Which are the parts that still are bright?  
I late fix added the left margin background for the BASIC code editor.

**Comment by chrisgleissner** [comment]
Hi Georg,

thanks for your fast reply. 

I have been playing around a bit more with the colors and achieved something that is fairly workable. The only part that still looks wrong is the menu colors. Both text and background color of the main menu items are bright, making them hard to read.

Here is the dark mode XML config I came up with. It would be great if something like this could be offered as a "one stop" solution that is activated with a "Enable Dark Mode" button in the color menu. I optimized these colors for the assembly view. Main code is white, labels are golden, operands are turquoise and comments are green. Background is not black but rather a dark gray, as is customary with modern dark modes as complete black would result in a high contrast which again can be painful on the eye after a while.

Just a baseline for further improvements, thought I would share in case you are interested or if anyone else runs into a similar problem and is looking for workable colors. 

<?xml version="1.0"?>
<C64StudioSettings>
  <EditorColors>
    <Color Element="NONE" FGColor="FFFFFFFF" BGColor="FF1F1F1F"/>
    <Color Element="CODE" FGColor="FFFFFFFF" BGColor="FF202020"/>
    <Color Element="LITERAL_STRING" FGColor="FF008000" BGColor="FF202020"/>
    <Color Element="LITERAL_NUMBER" FGColor="FF80FFFF" BGColor="FF202020"/>
    <Color Element="LABEL" FGColor="FFF9DF91" BGColor="FF202020"/>
    <Color Element="COMMENT" FGColor="FF80FF80" BGColor="FF202020"/>
    <Color Element="PSEUDO_OP" FGColor="FFFF8000" BGColor="FF202020"/>
    <Color Element="CURRENT_DEBUG_LINE" FGColor="FFFFFFFF" BGColor="FF8C8C00"/>
    <Color Element="EMPTY_SPACE" FGColor="FFFFFFFF" BGColor="FF272727"/>
    <Color Element="OPERATOR" FGColor="FF80FFFF" BGColor="FF202020"/>
    <Color Element="HIGHLIGHTED_SEARCH_RESULTS" FGColor="FF80FFFF" BGColor="FF202020"/>
    <Color Element="ERROR_UNDERLINE" FGColor="FFFF0000" BGColor="FF202020"/>
    <Color Element="SELECTED_TEXT" FGColor="FFFF8080" BGColor="FF202020"/>
    <Color Element="CONTROL_TEXT" FGColor="FFFFFFFF" BGColor="FF008000"/>
    <Color Element="BACKGROUND_CONTROL" FGColor="FFFFFFFF" BGColor="FF202020"/>
    <Color Element="CHANGED_DEBUG_ELEMENT" FGColor="FFFF0000" BGColor="FF202020"/>
    <Color Element="SELECTION_FRAME" FGColor="FF80FF80" BGColor="FF202020"/>
    <Color Element="BACKGROUND_BUTTON" FGColor="FFFFFFFF" BGColor="FF202020"/>
  </EditorColors>
</C64StudioSettings>

Thanks
Christian

**Comment by GeorgRottensteiner** [comment]
Thanks, I'll look into it! Just FYI, in the release there's a folder named "themes", there is a "Dark.xml", which could also be a base.
However when menu items are still bright, I need to adjust the code anyway.

**Comment by chrisgleissner** [comment]
Thanks, that's great. I'll check it out.

**Comment by GeorgRottensteiner** [comment]
Regarding the bright colors, you're referring to the highlighted menu items, tab headers and optionally the list control headers? Anything I've missed?

**Comment by chrisgleissner** [comment]
I think you got it. That's all the places I noticed.

**Comment by GeorgRottensteiner** [comment]
I haven't fixed every little part of it, but you can check out the webmisc link (where I usually place the WIP versions):
https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

The theme choice sounds like a really good idea, something that I should've noticed before :)

**Comment by chrisgleissner** [comment]
Thanks a lot, this looks much better. My Windows 11 (2022 update preview) is on systemwide dark mode, and using the version you just uploaded, C64 Studio picked that up right away and displayed the menu bars, etc. correctly. I think this is the right way to go. Ideally, it would just respect the configured system wide mode (light or dark), and your latest version seems to do this for most of the panels already.

**Comment by GeorgRottensteiner** [comment]
Respecting the system wide settings would be default. But once you go after theming, it's kinda all or nothing. Anything in between will always be wrong in a different config.
There could be an option overriding the color settings only for non system-control types.

**Comment by GeorgRottensteiner** [comment]
Closing this for now, as respecting system wide settings is a different issue

**Comment by chrisgleissner** [comment]
Thanks Georg, your help on this was much appreciated.
