### ISSUE TITLE
Debugging multifile C64 assembly

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#73]
I have a C64 project which is split in to multiple .asm files. In my firstfile.asm, I include my seconfile.asm with
`!source "secondfile.asm"`
All is fine and everything works. If I add a break point to the firstfile.asm, it works. Having a breakpoint in secondfile.asm, does not work.

The capability to debug the secondfile.asm is requested.

Second option: As the above may be complex, please add a functionality to combine sources in to one .asm file. This would be similar to Build->Preprocessed file, but has only added the `!source "file"` in their respective places. All others, like !bin is left as-is. I can then build and debug this single file when needed.

**Comment by GeorgRottensteiner** [comment]
That's all implemented and ought to work fine. I just tested with a simple file pair and it worked nicely.
Could be something about the setup of the project though. On the very first assembly C64Studio doesn't know that the second file is part of the final build.

If that doesn't help can you provide a bit more details, maybe even a really stripped down sample; plus, which VICE version you're using, and the full display of the "output" window.

**Comment by mokdevel** [comment]
>Could be something about the setup of the project though. On the very first assembly C64Studio doesn't know that the second file is part of the final build.

Could be. I have all the files in the solution explorer as a flat structure and included from the firstfile.asm (!source). Did I miss something? The project works perfectly when compiling from firstfile.

**Comment by GeorgRottensteiner** [comment]
Difficult to say, everything, that is done differently than I'm doing, is bound to be problematic :)
How do you set the breakpoint? By clicking into the border, or is it a data breakpoint or one with special settings (only load/store etc.)?

I think it would really help if you could do a small sample where it doesn't work for you. I know it's annoying, but could you also do a short write up how you, step by step, set the breakpoints and start debugging?

**Comment by mokdevel** [comment]
Sure, I'll provide an example later.

**Comment by mokdevel** [comment]
Using GTK3VICE-3.7-win64. I've set the debug start address in the project to where my code starts. I set a break point by clicking the border. run+debug.
- Code execution stops at a 'random place'. I hit Debug GO. The previously set breakpoint never triggers. 
- I pause the execution. Remove the breakpoint and reset to the same line by clicking the border. 
- run+debug and now the breakpoint is triggered. I can now step through code, set new breakpoints etc. 

Not sure if this a Vice thing or smth else, but from my point of view the case can be closed. I now know how to use breakpoints even if it's a little tricky.

Thank you for the support and amazing tool. You have re-lit my passion for c64 coding!

**Comment by mokdevel** [comment]
>Just out of curiousity, what do you change the debug start address to?

I changed it to the address where my program starts. No reason, I was just desperate. :-)

**Comment by GeorgRottensteiner** [comment]
Closing this, as it's sort of resolved

**Comment by mokdevel** [comment]
It could've been an issue on my end. A clean installation of tools on a separate machine and I have no issue. Keep it closed. Thanks for the support.

**Comment by GeorgRottensteiner** [comment]
Thanks for double checking! Feel free to reopen, if you find it happens again.
