### ISSUE TITLE
Import from HEX to character editor

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#74]
Please include an option to import from HEX to character editor. This feature is in the sprite editor and is needed for the character editor too.

**Comment by GeorgRottensteiner** [comment]
Added with commit #87b596bf76789b9935cbf78764cf2afe0128b2b3

Is also available in the WIP version (https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip)
->Careful, it does say WIP for a reason

**Comment by mokdevel** [comment]
I tried the WIP version (7.3.3). I could not find a 'from HEX' option. 

(BTW, importing from binary should have an option to ignore N bytes. Typically files have a 2 byte load address in the beginning and skipping those would make the binary import perfect. Shall I raise another issue?)

**Comment by GeorgRottensteiner** [comment]
Do you maybe refer to the "Charset screen editor"? I've added the import from hex to the "charset editor".
Support for both charset and/or screen data?

No need to add a new issue for the binary skip, I'll see to add it directly.

**Comment by mokdevel** [comment]
Sry, mybad. Charset editor has it as I wished. My eyes played tricks on me.

>No need to add a new issue for the binary skip, I'll see to add it directly.

Thanks.
