### ISSUE TITLE
Use color palette in editors as Vice uses

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#76]
When editing multicolor charsets/screens in C64studio, the colors are 'darker' than what Vice is using. Vice color palette is closer to the original C64.

**Comment by GeorgRottensteiner** [comment]
I know I'm over a year behind, but I'm currently working on allowing edited default palettes, and choosing from a list.
It's surprisingly complex to manage palette updates all over the place.
