### ISSUE TITLE
Right click to paint with background (clear pixels)

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#77]
The right click should paint with background color (clear pixels) in character and sprite editors. So, I can draw with left button with the chosen color and clear misplaced pixels with right button.

Currently, I need to select background color to clear pixels.

**Comment by GeorgRottensteiner** [comment]
That is an general option already, File->Preferences->General->Editor Behaviour -> Right Click is Paint with BG Color

HTH!

**Comment by mokdevel** [comment]
Thanks! You're right and works as expected.
