### ISSUE TITLE
Cancel exits C64 Studio

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#78]
- Have a project open
- Write some text in .asm. Don't save.
- Hit X in the upper right corner of tool. A dialog notifies about "unsaved changes, save now?".
- Options given are yes/no/cancel
- Press cancel to go back to the tool. The issue: The tool exits without saving changes nor returning to the tool.

Tested with WIP too.

**Comment by GeorgRottensteiner** [comment]
I was looking at the wrong part all the time. Fixed with commit e70c3ad2327dfd43f2af881ca67050db1dd12a64.

Also uploaded a new WIP version for this. Thanks!

**Comment by mokdevel** [comment]
Shall I use the same link as previously for the WIP? It shows 7.3.3 as the version.

**Comment by GeorgRottensteiner** [comment]
Yeah, that's fine. I'm not always increasing the version number.

**Comment by mokdevel** [comment]
Thanks. Tested and works as expected.
