### ISSUE TITLE
Charscreen reverse character behaviour

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#80]
When writing text (Direct Text Entry) with 'Reverse Characters' and 'Affect characters' enabled, it only reverses the character and does not write anything on screen. Disabling 'Reverse Characters' works as expected. I have a need to write in reverse.

Tested with latest WIP (7.3.5)

**Comment by GeorgRottensteiner** [comment]
That's something I've never even tried. Exactly how are you activating "reverse characters"? There is no option for that (yet)?

**Comment by mokdevel** [comment]
I have a .scharscreen. Double click to edit (.. obvious :-) )
* Click [T] - Direct text entry
* Click 'Reverse characters button' - the one on the right side of Affect colors. 
** This will disable the 'Affect characters' function - the one on the left side of Affect colors. 
* Enable 'Affect characters'

**Comment by GeorgRottensteiner** [comment]
My god, I wrote this thing and didn't see that option. Thanks, will fix!

**Comment by mokdevel** [comment]
While at it, using mouse to paint in 'reverse character' mode needs a click on every character. If you keep mouse button pressed, it feels like it is in a 'on-off-on-off-on-off-...' mode and chars here and there are changing to reverse.

**Comment by GeorgRottensteiner** [comment]
Both fixed with commit #3e39841f8207e58c1d0b2ddaa9e73a65c3c55eb4.
Looks like I was half way there and then got side tracked.

New WIP version is also up.

**Comment by mokdevel** [comment]
Perfect! Both issues fixed and works as expected. A small wish - please update the version number of WIP on every release - makes it easier to know if there is an update.

**Comment by GeorgRottensteiner** [comment]
Great, closing this. Yeah, I need to do some automatic versioning there.
