### ISSUE TITLE
Charscreen reverse mode backspace clears in non-reverse.

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#81]
When in Charscreen editor and in reverse mode writing text with Direct Text Entry, backspace cleans in non-reverse. Backspace normally paint space ($20) and in reverse mode should paint reverse space ($a0). Currently it paints the non-reverse space.

Tested in WIP (7.3.5)

**Comment by GeorgRottensteiner** [comment]
Fixed with commit ca4dfe95842ff71df13aa8a71e273f668216f64f

Also uploaded as WIP version.
