### ISSUE TITLE
Align value one off

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#83]
Not a bug but I find this confusing. If it's by design like this, please close the case.

I would expect that `!align 8,0` would align code to next address 0 or 8 address. It actually does nothing. With `!align 7,0` I get what I want. The same 'one off' behaviour is with other addresses:
`!align $f,0` -> an address divided by $10
`!align $1f,0` -> an address divided by $20
...
`!align $ff,0` -> an address divided by $100

**Comment by GeorgRottensteiner** [comment]
It's a Pseudo Opcode I've added to keep compatible with ACME. Yes, it is confusing, but I need to keep it to stay compatible.

The first value is a mask to AND with. It keeps filling with the fill value until the current address & the AND Mask return the second comparison value.

I think !realign is probably more like what you expected it to be:

!realign $2               ; wait for even address
!realign 256             ; align code to page border
