### ISSUE TITLE
Sprite Preview "Save as GIF" Produces Broken GIF

### ISSUE THREAD

**Issue by yetanotherfrank** [GeorgRottensteiner/C64Studio#90]
When trying to export my sprite animation as a GIF using "Save as GIF", the resulting GIF has the correct size, but shows only a white rectangle in the browser. Other image apps like Windows Photo even refuse to load it, claiming it contains an incorrect frame.
Attached is a .spriteproject and the broken GIF.
[sprite-save-as-gif-bug.zip](https://github.com/GeorgRottensteiner/C64Studio/files/11800232/sprite-save-as-gif-bug.zip)
This is the result when using the net3.5 version of C64Studio 7.41. Using the net6.0-windows version, there is even a run-time error when trying to "Save as GIF".

**Comment by GeorgRottensteiner** [comment]
Ah, that one went bust when I changed all internal images to 32bit. Fixed with commit #5d14df37433101e91ffb947deeb3c9ab92472374

Uploaded a WIP version at https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip

Thanks!

**Comment by yetanotherfrank** [comment]
Just retested with you WIP version (again with the net3.5 version, which seems to work best for me with a HiDPI display), and it now works like a charm - impressive fix within a couple of hours! 👏
