### ISSUE TITLE
Huge settings.dat hangs editor while closing

### ISSUE THREAD

**Issue by truebluepl** [GeorgRottensteiner/C64Studio#91]
While usings C64Studio settings.dat file grows up (to 1-2 MB) and prevent closing editor properly (force closing or killing proccess is needed).
I don't know what is reason. Maybe undo operation or replace on big parts of code.
When settings.dat is huge also opening find/replace window makes it hung for a while.

**Comment by GeorgRottensteiner** [comment]
Ah, this is one bug that I fortunately already squashed. I kept adding duplicates to the Find/Replace history.
Please try with the WIP version from https://www.georg-rottensteiner.de/webmisc/C64StudioRelease.zip
