### ISSUE TITLE
How to assembly 65816 in recent commits?

### ISSUE THREAD

**Issue by xlar54** [GeorgRottensteiner/C64Studio#94]
This is just a question.. but Im having trouble assembling 65816 code, even though Im suing !cpu 65816.  Tracing through, it still goes through Create6510() function.   Is there a target cpu setting in the UI for a file or project that Im not seeing?

**Comment by GeorgRottensteiner** [comment]
Using !cpu 65816 inside the source should do the trick.

There's a unit test showing all opcodes in TestAssembly65816Opcodes in TestAssembler.CPU.cs.

**Comment by GeorgRottensteiner** [comment]
The Create6510 is the starting default, once the code hits the !cpu 65816 directive it will switch.
Closing this, if it still won't work, don't hesitate to reopen
