### ISSUE TITLE
Request: Screen editor zoom

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#98]
Would it be possible to have 2x and 4x (or free x) modes of zoom in Screen editor (multicolor 320x200 images etc..)? On a large screen it would be great to see the image bigger to see the pixels better when editing.

(Currently I can achieve the same with Windows magnifying glass 200% when editing)

**Comment by GeorgRottensteiner** [comment]
As replied in the other request, the editor needs to be redone :)

**Comment by GeorgRottensteiner** [comment]
The graphic screen editor now boasts several zoom modes, hope it works as you expected.
