### ISSUE TITLE
Request: In screen editor, select colors for mouse buttons

### ISSUE THREAD

**Issue by mokdevel** [GeorgRottensteiner/C64Studio#99]
It would be great to be able to select colors for RMB and LMB. Currently only LMB is usable and color is picked from the color list. If I'm pixeling in red and green, I need to constantly change the color from the color list. I'd rather have red in RMB and green in LMB.

**Comment by GeorgRottensteiner** [comment]
The graphic screen editor needs a major overhaul. It's current incarnation was thought to be used to do little touchups, do the painting outside and paste it inside.
More and more requests ask for a rather real painting tool, might be one of the things I tackle next.

**Comment by mokdevel** [comment]
Thanks for the reply. A real painting tool would be great. The process of painting outside and paste it inside works, but I'd love to have everything in one place. You may close both cases.

**Comment by GeorgRottensteiner** [comment]
Closing, but keeping the other issue open as reminder (sometimes it helps)
